version: '3'
services:
  hoge:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-hoge
    container_name: 'hoge'
#    working_dir: '/opt/test'
#    tty: true
#    volumes:
#      - ./data:/root/data
#    command: pytest test.py
