version: '3'
services:
  test01:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-test01
  test02:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile-test02
#    container_name: 'hoge'
#    working_dir: '/opt/test'
#    tty: true
#    volumes:
#      - ./data:/root/data
#    command: pytest test.py
