version: 2
jobs:
  build:
#    branches:
#      only:
#        - hoge
    machine: true
    steps:
      - checkout
      - run:
          name: Running tests
          command: docker-compose up --build
#          command: cat /proc/cpuinfo && cat /proc/meminfo
  test:
#    branches:
#      only:
#        - hoge
    machine: true
    steps:
      - checkout
      - run:
          name: Hoge
          command: pytest test.py

workflows:
  version: 2
  build_and_test:
    filters:
      branches:
        only: develop
    jobs:
      - build
      - test:
          requires:
            - build