version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Running tests
          command: docker-compose up --build
#          command: cat /proc/cpuinfo && cat /proc/meminfo
  test:
    machine: true
    steps:
      - checkout
      - run:
        name: Hoge
        command: pytest test.py

workflows:
  version: 2
  build_and_test:
    jobs:
#      - build
      - test:
#          requires:
#            - build
