version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
#      - run: docker-compose up --build
      - run:
          name: Running tests
          command: docker-compose up --build
